name: 网格交易
description: 这是一个网格交易流程，自动高抛低吸，卖出、买入股票
begin:
  - name: 网格交易准备
    flow: general
    description: 当前页面需要在首页 
steps:
  - name: 首页
    layout: home.xml
    screenshot: home.png
    description: 这是Home,点击【条件单】
    step: 1
  - name: 条件单
    layout: tiao-jian-dan.xml
    screenshot: tiao-jian-dan0.png
    description: 这是条件单页面
    step: 2
  - name: 网格交易
    layout: wang-ge-jiao-yi.xml
    screenshot: wang-ge-jiao-yi.png
    description: 这是网格交易页面
    step: 3
  - name: 股票搜索
    layout: gu-piao-sou-suo.xml
    screenshot: gu-piao-sou-suo.png
    description: 这是股票搜索页面
    step: 4
  - name: 股票搜索结果
    layout: stock-search-result.xml
    screenshot: stock-search-result.png
    description: 这是股票搜索结果页面
    step: 5
  - name: 网格交易填好股票代码
    layout: wang-ge-jiao-yi-with-stock.xml  
    screenshot: wang-ge-jiao-yi-with-stock0.png
    description: 这是网格交易填好股票代码页面
    step: 6
  - name: 网格交易确认
    layout: wang-ge-jiao-yi-confirm.xml
    screenshot: wang-ge-jiao-yi-confirm.png
    description: 这是网格交易确认页面
    step: 7
  - name: 条件单创建成功
    layout: wang-ge-jiao-yi-success.xml
    screenshot: wang-ge-jiao-yi-success.png
    description: 这是网格交易成功页面
    step: 8
  - name: 我的条件单
    layout: my-condition-orders.xml
    screenshot: my-condition-orders.png
    description: 这是我的条件单页面
    step: 9
ends:
  - name: 提交结果
    layout: ti-jiao-jie-guo.xml
    screenshot: ti-jiao-jie-guo.png
    description: 这是提交结果页面，结束[网格交易]流程
